name: commit-and-push

on:
  workflow_call:
    inputs:
      authorName:
        required: false
        type: string
        default: k8slt
      authorEmail:
        required: false
        type: string
        default: klt@groups.vmware.com
      repository:
        required: true
        type: string
      branch:
        required: false
        type: string
        default: develop
      folder:
        required: false
        type: string
        default: .
    secrets:
      githubToken:
      githubDeployPrivateKey:
    outputs:
      yttReleaseValues:
        description: "ytt values file content"
        value: ${{ jobs.get_assets_sha.outputs.result }}

jobs:
  commit-and-push:
    runs-on: ubuntu-latest
    steps:
    - name: Commit & Push changes
      env:
        AUTHOR_NAME: ${{ inputs.authorName }}
        AUTHOR_EMAIL: ${{ inputs.authorEmail }}
        REPOSITORY: ${{ inputs.repository }}
        BRANCH: ${{ inputs.branch }}
        FORCE: false
        GITHUB_TOKEN: ${{ secrets.githubToken }}
        GITHUB_DEPLOY_PRIVATE_KEY: ${{ secrets.githubDeployPrivateKey }}
      run: |
        set -e
        
        timestamp=$(date -u +"%Y-%m-%dT%H:%M:%SZ")
        
        AUTHOR_EMAIL=${AUTHOR_EMAIL:-'github-actions[bot]@users.noreply.github.com'}
        AUTHOR_NAME=${AUTHOR_NAME:-'github-actions[bot]'}
        MESSAGE=${MESSAGE:-"chore: autopublish ${timestamp}"}
        FORCE=${FORCE:-false}
        REPOSITORY=${REPOSITORY:-$GITHUB_REPOSITORY}
        
        echo "Push to branch $BRANCH";
        [ -z "${BRANCH}" ] && {
          echo 'Missing branch';
          exit 1;
        };
        
        if [ -z "${GITHUB_TOKEN}" ] && [ -z "${GITHUB_DEPLOY_PRIVATE_KEY}" ]; then
            echo 'Missing required input "github_token: ${{ secrets.GITHUB_TOKEN }} OR "github_deploy_private_key: ${{ secrets.GITHUB_DEPLOY_PRIVATE_KEY }}".';
            exit 1;
        fi
        
        if ${FORCE}; then
            _FORCE_OPTION='--force'
        fi
        
        remote_repo="https://${GITHUB_ACTOR}:${GITHUB_TOKEN}@github.com/${REPOSITORY}.git"
        
        if [ -n "${GITHUB_DEPLOY_PRIVATE_KEY}" ]; then
          remote_repo="git@github.com:${REPOSITORY}"
        
          tempkey=`basename $0`
          TMP_DEPLOY_PRIV_KEY=`mktemp /tmp/${tempkey}.XXXXXX` || exit 1
          echo "${GITHUB_DEPLOY_PRIVATE_KEY}" > $TMP_DEPLOY_PRIV_KEY
          eval $(ssh-agent -s)
          ssh-add ${TMP_DEPLOY_PRIV_KEY}
        fi
        
        cd ${{ inputs.folder }}
        
        git config http.sslVerify true
        git config --local user.email "${AUTHOR_EMAIL}"
        git config --local user.name "${AUTHOR_NAME}"
        
        git add -A
        
        git commit -m "${MESSAGE}" $_EMPTY || exit 0
        
        git push "${remote_repo}" HEAD:"${BRANCH}" --follow-tags $_FORCE_OPTION;
