name: published_release

on: [repository_dispatch]

jobs:
  process-release-information:
    runs-on: ubuntu-latest
    outputs:
      yttValuesFile: ${{ steps.get-checksums-from-release.outputs.result }}
    steps:
      - uses: actions/github-script@v5
        id: get-checksums-from-release
        if: startsWith(github.ref, 'refs/tags/') && ${{ !env.ACT }}
        with:
          result-encoding: string
          script: |
            var crypto = require('crypto');

            const owner = context.payload.client_payload.repo.split("/")[0]
            const repo = context.payload.client_payload.repo.split("/")[1]
            
            // https://docs.github.com/en/rest/reference/repos#list-releases
            // https://octokit.github.io/rest.js/v18#repos-list-releases
            var releases = await github.rest.repos.listReleases({
              owner: owner,
              repo: repo
            });
            
            var crypto = require('crypto')
            var fs = require('fs')
            const url = require('url');
            const https = require('https');
            
            checksums = {}
            for (const r of releases["data"]) {
              console.log(`${r.tag_name} == ${ context.payload.client_payload.tagName }`)
              if (!r.draft && r.tag_name == context.payload.client_payload.tagName) {
                for (const asset of r.assets) {
                  var release_asset = await github.rest.repos.getReleaseAsset({ headers: {accept: `application/octet-stream`}, accept: `application/octet-stream`, owner: owner, repo: repo, asset_id: asset.id });
                  const hash = crypto.createHash('sha256');
            
                  let http_promise = new Promise((resolve, reject) => {
                    https.get(release_asset.url, (stream) => {
                      stream.on('data', function (data) {
                        hash.update(data);
                      });
                      stream.on('end', function () {
                        checksums[asset.name]= hash.digest('hex');
                        resolve(`${asset.name}`);
                      });
                    });
                  });
                  await http_promise;
                }
                break
              }
            }
            console.log(checksums)
            
            githubURL = `github.com/${context.payload.client_payload.repo}`
            result = `
            #@data/values
            ---
            product: ${context.payload.client_payload.toolName}
            version: ${context.payload.client_payload.tagName}
            github:
              url: ${githubURL}
            assets:
            `
            
            for (const [key, value] of Object.entries(checksums)) {
              if (key.indexOf(context.payload.client_payload.toolName) != -1) {
              keyParts = key.split('.')[0].split("-")
              result += `
              - os: ${keyParts[1]}
                arch: ${keyParts[2]}
                shasum: ${value}
                filename: ${key}
              `
              }
            }
            
            console.log(result)
            
            return result
      - name: Create release file
        run: |
          cat <<EOF >release.yml
          ${{ steps.get-checksums-from-release.outputs.result }}
          EOF
      - name: Upload Release information file
        uses: actions/upload-artifact@v2
        with:
          name: ytt-data-values-for-release
          path: ./release.yml
  prepare-homebrew-file:
    runs-on: ubuntu-latest
    needs: process-release-information
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Download ytt data values file with release information
        uses: actions/download-artifact@v2
        with:
          name: ytt-data-values-for-release
          path: ./tmp/release.yml
      - name: Generate Homebrew File
        run: |
          set -e -x
          curl -L https://carvel.dev/install.sh | bash
          filename="./${{ github.event.client_payload.toolName }}.rb"
          
          ./scripts/generate_homebrew_formula.sh ./tmp/release.yml > $filename
  
          cat $filename
      - name: Upload Homebrew File
        uses: actions/upload-artifact@v2
        with:
          name: homebrew-formula
          path: ./${{ github.event.client_payload.toolName }}.rb
  release-on-homebrew:
    runs-on: ubuntu-latest
    needs: prepare-homebrew-file
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          persist-credentials: false
          repository: vmware-tanzu/homebrew-carvel
          ref: develop
      - name: Download updated homebrew formula
        uses: actions/download-artifact@v2
        with:
          name: homebrew-formula
      - name: View homebrew formula
        run: |
          filename="./${{ github.event.client_payload.toolName }}.rb"
          cat $filename

  prepare-install-sh:
    runs-on: ubuntu-latest
    needs: process-release-information
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Download ytt data values file with release information
        uses: actions/download-artifact@v2
        with:
          name: ytt-data-values-for-release
          path: ./tmp/release.yml
      - name: Checkout website repository
        uses: actions/checkout@v2
        with:
          persist-credentials: false
          repository: vmware-tanzu/carvel
          path: carvel
          ref: develop
      - name: generate install.sh
        run: |
          set -e -x
          
          ./scripts/generate_install_sh.sh ${{ github.event.client_payload.toolName }} ./carvel/site/static/install.sh > ./install.sh
          
          cat ./install.sh
      - name: Generate Homebrew File
        run: |
          set -e -x
          curl -L https://carvel.dev/install.sh | bash
          filename="./${{ github.event.client_payload.toolName }}.rb"
          
          ./scripts/generate_homebrew_formula.sh ./tmp/release.yml > $filename
          
          cat $filename
      - name: Upload Homebrew File
        uses: actions/upload-artifact@v2
        with:
          name: homebrew-formula
          path: ./${{ github.event.client_payload.toolName }}.rb
