name: published_release

on:
  push:
    paths:
      - releases.yaml
jobs:
  update-install-sh:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Install ytt
        uses: vmware-tanzu/carvel-setup-action@v1
        with:
          only: ytt
      - run: |
          echo "bamm"
          ytt --data-values-file releases.yaml -f scripts/install_sh/install.sh.txt --output-files tmp
          cat tmp/install.sh.txt
