name: published_release

on:
  push:
    paths:
      - releases.yaml
jobs:
  generate-new-install-sh:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Install ytt
        uses: vmware-tanzu/carvel-setup-action@v1
        with:
          only: ytt
      - run: |
          ytt --data-values-file releases.yaml -f scripts/install_sh/install.sh.txt --output-files tmp
          cat tmp/install.sh.txt
          mv tmp/install.sh.txt install.sh
          chmod u+x install.sh
      - name: Upload install.sh
        uses: actions/upload-artifact@v2
        with:
          name: new-install-sh
          path: install.sh
  update-install-sh:
    needs: generate-new-install-sh
    uses: joaopapereira/releaser/.github/workflows/commit-and-push.yml@main
    secrets:
      githubToken: ${{ secrets.ACCESS_TOKEN }}
    with:
      authorName: joaopapereira
      authorEmail: joaod@vmware.com
      repository: joaopapereira/carvel
      branch: main
      artifactName: new-install-sh
      artifactPath: ./site/static/
