name: published_release

on:
  push:
    paths:
      - releases.yaml
jobs:
  update-install-sh:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "bamm"
          ytt --data-values-file releases.yaml -f scripts/install_sh/install.sh.txt --output-files tmp
          cat tmp/install.sh.txt
